service: qa-events-agent

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-2

functions:
  simpleSuccess:
    handler: handler.simpleSuccess
    environment:
      IOPIPE_TOKEN: ${env:IOPIPE_TOKEN}
    role: ${env:IAM_ROLE}
    events:
      - schedule: rate(10 minutes)
